spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
app:
  message: "Welcome to the Spring Boot Application! - DEV Environment"